version: '3.8'

services:
  mkdocs-material:
    container_name: mkdocs
    image: squidfunk/mkdocs-material:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
     - ./:/docs
